apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    seldon-server-name: triton-gpu
  name: triton-models-triton-gpu-0
  namespace: seldon-mesh
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-dynamic-sc
---
apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: triton-gpu
spec:
  serverConfig: triton
  podSpec:
    containers:
    - name: triton
      image: nvcr.io/nvidia/tritonserver:23.09-py3
      resources:
        limits:
          memory: 8Gi
          nvidia.com/gpu: 1
        requests:
          memory: 8Gi
          nvidia.com/gpu: 1
      volumeMounts:
        - name: triton-models
          mountPath: /var/models
      env:
      - name: TRANSFORMERS_CACHE
        value: /var/models/.cache
    volumes:
    - name: triton-models
      persistentVolumeClaim:
        claimName: triton-models-triton-gpu-0
    
    tolerations:
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"