---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}-nginx
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.nginxAuth.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: nginx
