---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}-backend
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.service.backendPort }}
      protocol: TCP
      name: http
  selector:
    name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bailo.fullname" . }}-frontend
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendPort }}
      protocol: TCP
      name: http
  selector:
    name: frontend
