---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bailo.fullname" . }}-builder
  labels:
    {{- include "bailo.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bailo.fullname" . }}-builder
rules:
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["build.openshift.io"]
  resources: ["buildconfigs/instantiatebinary"]
  verbs: ["create"]
- apiGroups: ["build.openshift.io"]
  resources: ["builds/log"]
  verbs: ["get"]
- apiGroups: ["build.openshift.io"]
  resources: ["builds"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bailo.fullname" . }}-builder
subjects:
- kind: ServiceAccount
  name: {{ include "bailo.fullname" . }}-builder
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "bailo.fullname" . }}-builder
  apiGroup: rbac.authorization.k8s.io
