{{- if .Values.aws.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ingress.service.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nginxAuth.port }}
      targetPort: {{ .Values.nginxAuth.port }}
  selector:
    name:  nginx
{{- end }}
